TC/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
path('signup/', views.signup, name = "sign up"),
path('createaccount/', views.prueba, name = "ingreso"),
path('', views.homeTC, name = "TC home"),
path('logout/', views.signout, name = 'log out'),
path('login/', views.signin, name = "login"),
path('youarenotlogged/', views.ingresa, name = "no")
]

TeamMembers/urls.py
from django.urls import path
from . import views
from django.conf import settings


urlpatterns = [
path('agents/', views.Agents, name = "agents"),
path('agents/add/', views.AddAgent, name = "add agent"),
path('agents/<int:agent_id>/', views.AgentInfo, name = "agent info"),
path('agents/<int:agent_id>/requested/', views.requested, name = "requested by agent"),
path('agents/<int:agent_id>/pendings/', views.pendings, name = "pending requests"),
path('agents/<int:agent_id>/completed/', views.completed, name = "completed requests")
]

TicketSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from Tickets.views import home
from django.conf.urls.static import static

urlpatterns = [
    path("", home, name = "app home"),
    path("admin/", admin.site.urls),
    path('ticket/', include('Tickets.urls')),
    path('TC/', include('TC.urls')),
    path('Team/', include("TeamMembers.urls"))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

TeamMembers/models.py
from django.db import models

# Create your models here.
class TeamMembers(models.Model):
	name = models.CharField(max_length=100, verbose_name="Agent's Name")
	phone = models.CharField(max_length=100, verbose_name="Phone Number")
	email = models.CharField(max_length=100, verbose_name="Email")
	offer = models.IntegerField(default=0)
	addendum = models.IntegerField(default=0)
	listing = models.IntegerField(default = 0)
	mls_attachments = models.IntegerField(default = 0)
	mls_search = models.IntegerField(default = 0)
	dotloop = models.IntegerField(default = 0)

	
	def __str__(self):
		return str(self.name)

TeamMembers/forms.py
from django.forms import ModelForm
from django import forms
from .models import TeamMembers

class TeamForm(ModelForm):
	"""docstring for TeamForm"""
	class Meta:
		model = TeamMembers
		fields = ['name', 'phone','email']

TeamMembers/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import TeamMembers
from .forms import TeamForm
from Tickets.models import *
from Tickets.forms import *
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.db.models import Count
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required
def Agents(request):
	agents = TeamMembers.objects.all()
	offer = CreateOffer.objects.values('agent').annotate(Count('agent'))
	addendum = CreateAddendum.objects.values('agent').annotate(Count('agent'))
	listing = CreateListing.objects.values('agent').annotate(Count('agent'))
	mls_attachments = CreateMLSsheet.objects.values('agent').annotate(Count('agent'))
	mls_search = CreateSearch.objects.values('agent').annotate(Count('agent'))
	dotloop = CreateDotloop.objects.values('agent').annotate(Count('agent'))

	a = offer.values_list('agent','agent__count')
	b = addendum.values_list('agent', 'agent__count')
	c = listing.values_list('agent','agent__count')
	d = mls_attachments.values_list('agent', 'agent__count')
	e = mls_search.values_list('agent','agent__count')
	f = dotloop.values_list('agent', 'agent__count')

	for agent in agents:
		for count in a:
			if agent.id == count[0]:
				agent.offer = count[1]
		for count in b:
			if agent.id == count[0]:
				agent.addendum = count[1]
		for count in c:
			if agent.id == count[0]:
				agent.listing = count[1]
		for count in d:
			if agent.id == count[0]:
				agent.mls_attachments = count[1]
		for count in e:
			if agent.id == count[0]:
				agent.mls_search = count[1]
		for count in f:
			if agent.id == count[0]:
				agent.dotloop = count[1]
		agent.save()
	return render(request, 'agents.html', {'encabezado':"Team", "agents":agents})

@login_required
def AddAgent(request):
	if request.method == "POST":
		form = TeamForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('agents')
	else:
		form = TeamForm()
	return render(request, 'addagent.html', {'form':form, 'encabezado':'Add Agent'})
	
@login_required
def AgentInfo(request, agent_id):
	agent = get_object_or_404(TeamMembers, pk = agent_id)
	return render(request, 'agentinfo.html',{'encabezado':agent.name, 'agent':agent})
@login_required
def requested(request, agent_id):
	agent = get_object_or_404(TeamMembers, pk = agent_id)
	offers = CreateOffer.objects.filter(agent=agent_id)
	addendums = CreateAddendum.objects.filter(agent=agent_id)
	listings = CreateListing.objects.filter(agent=agent_id)
	mlssheets = CreateMLSsheet.objects.filter(agent=agent_id)
	mls_searches = CreateSearch.objects.filter(agent=agent_id)
	dotloops = CreateDotloop.objects.filter(agent=agent_id)
	return render(request,'requested.html',{'encabezado':f"Requested by {agent.name}",'offers':offers,
					'addendums':addendums,'listings':listings,'mlssheets':mlssheets,'mls_searches':mls_searches,
					'dotloops':dotloops})
@login_required
def pendings(request, agent_id):
	agent = get_object_or_404(TeamMembers, pk = agent_id)
	offers = CreateOffer.objects.filter(agent=agent_id, completed__isnull = True)
	addendums = CreateAddendum.objects.filter(agent = agent_id, completed__isnull = True)
	listings = CreateListing.objects.filter(agent = agent_id, completed__isnull = True)
	mlssheets = CreateMLSsheet.objects.filter(agent = agent_id, completed__isnull = True)
	mls_searches = CreateSearch.objects.filter(agent = agent_id, completed__isnull = True)
	dotloops = CreateDotloop.objects.filter(agent = agent_id, completed__isnull = True)
	return render(request, 'pendings.html', {'encabezado':f"Pending requests of {agent.name}", "offers":offers,
		'addendums':addendums,'listings':listings, 'mlssheets':mlssheets,'mls_searches':mls_searches, 'dotloops':dotloops})
@login_required
def completed(request, agent_id):
	agent = get_object_or_404(TeamMembers, pk = agent_id)
	offers = CreateOffer.objects.filter(agent=agent_id, completed__isnull = False)
	addendums = CreateAddendum.objects.filter(agent=agent_id, completed__isnull = False)
	listings = CreateListing.objects.filter(agent=agent_id, completed__isnull = False)
	mlssheets = CreateMLSsheet.objects.filter(agent=agent_id, completed__isnull = False)
	mls_searches = CreateSearch.objects.filter(agent=agent_id, completed__isnull = False)
	dotloops = CreateDotloop.objects.filter(agent=agent_id, completed__isnull = False)
	return render(request, 'completed.html', {'encabezado':f"Completed requests of {agent.name}", 'offers':offers,
		'addendums':addendums, 'listings':listings, 'mlssheets':mlssheets, 'mls_searches':mls_searches, 'dotloops':dotloops})

TeamMembers/templates/addagent.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
	form{
		text-align: justify;
		align-content: center;
	}
	#id_name, #id_phone, #id_email{
		text-align: justify;
		width: 350px;
		align-content: center;
	}
</style>
<br>
<form action="{% url 'add agent' %}" method="POST">
	{% csrf_token %}
  <div class="form-group">
    {% for field in form %}
      {{ field.label_tag }}<br>
      {{ field }}<br>
    {% endfor %}
  </div>
  <button class="btn btn-primary">
    submit
  </button>
</form>

{% endblock %}

TeamMembers/templates/agentinfo.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container">
	<article class="card">
		<!--div class="background">
			<img src="{{agent.picture.url}}" alt="profile">
		</div-->
		<div class="content">
			<h1>{{agent.name}}</h1>
			<p>Info:</p>
			<ul class="chips">
			<li class="chip">Email: {{agent.email}}</li>
			<li class="chip">Phone number: {{agent.phone}}</li>	
			</ul>
			<div class="action-buttons" style="display: inline-flex;padding: 5px;">
				<h1><a href="{% url 'requested by agent' agent.id %}" class="btn btn-info" role="button" title="Requested" style="flex: 1; margin-right: 10px;">All Request</a></h1>
				<h1><a href="{% url 'pending requests' agent.id %}" class="btn btn-warning" role="button" title="Pending" style="flex: 1; margin-right: 10px;">Pending</a></h1>
				<h1><a href="{% url 'completed requests' agent.id %}" class="btn btn-secondary" role="button" title="Completed" style="flex: 1; margin-right: 10px;">Completed</a></h1>

			</div>

		</div>
	</article>
</div>

{% endblock %}

TeamMembers/templates/agents.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<table style="width: 100%;border-collapse: separate;">
	<!-- Headers -->
	<tr bgcolor="#00CDCD">
		<th style="border: 1px solid #ccc; padding: 8px;">Agent's Name</th>
		<th style="border: 1px solid #ccc; padding: 8px;">Phone Number</th>
		<th style="border: 1px solid #ccc; padding: 8px;">Email</th>
		<th style="border: 1px solid #ccc; padding: 8px;">Offers</th>
		<th style="border: 1px solid #ccc; padding: 8px;">Addendums</th>
		<th style="border: 1px solid #ccc; padding: 8px;">Listings</th>
		<th style="border: 1px solid #ccc;padding: 8px;">MLS Sheet/Attachments</th>
		<th style="border: 1px solid #ccc; padding: 8px;">MLS Search</th>
		<th style="border: 1px solid #ccc; padding: 8px;">Dotloop</th>
	</tr>
	<!-- Table Data -->
	{% for agent in agents %}
	<tr>
		<td style="border: 1px solid #ccc; padding: 8px;"><a href="{% url 'agent info' agent.id %}">{{agent.name}}</a></td>
		<td style="border: 1px solid #ccc; padding: 8px;">{{agent.phone}}</td>
		<td style="border: 1px solid #ccc; padding: 8px;">{{agent.email}}</td>
		<td style="border: 1px solid #ccc; padding: 8px;">{{agent.offer}}</td>
		<td style="border: 1px solid #ccc; padding: 8px;">{{agent.addendum}}</td>
		<td style="border: 1px solid #ccc; padding: 8px;">{{agent.listing}}</td>
		<td style="border: 1px solid #ccc; padding: 8px;">{{agent.mls_attachments}}</td>
		<td style="border: 1px solid #ccc; padding: 8px;">{{agent.mls_search}}</td>
		<td style="border: 1px solid #ccc; padding: 8px;">{{agent.dotloop}}</td>
	</tr>
	{% endfor %}
	
</table>

{% endblock %}

TeamMembers/templates/completed.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<table style="width: 100%;border-collapse: collapse;">
	<tr bgcolor="#ADD8E6">
		<th style="border: 1px solid #bbb;padding: 5px;">Request</th>
		<th style="border: 1px solid #bbb;padding: 5px;">Address / Client</th>
		<th style="border: 1px solid #bbb;padding: 5px;">Request Time</th>
		<th style="border: 1px solid #bbb;padding: 5px;">Status</th>
	</tr>
	
		{% for offer in offers %}
		<tr>
		<td><a href="{% url 'offer details' offer.id %}">Offer</a></td>
		<td>{{offer.address}}</td>
		<td>{{offer.created}}</td>
		<td>
			{% if offer.completed %}
			Completed {{offer.completed}}
			{% else %}
			Pending
			{% endif %}
		</td>
		</tr>
		{% endfor %}

		{% for addendum in addendums %}
		<tr>
		<td><a href="{% url 'addendum details' addendum.id %}">Addendum</a></td>
		<td>{{addendum.address}}</td>
		<td>{{addendum.created}}</td>
		<td>
			{% if addendum.completed %}
			Completed {{addendum.completed}}
			{% else %}
			Pending
			{% endif %}
		</td>
		</tr>
		{% endfor %}

		{% for listing in listings %}
		<tr>
		<td><a href="{% url 'listing details' listing.id %}">Listing</a></td>
		<td>{{listing.address}}</td>
		<td>{{listing.created}}</td>
		<td>
			{% if listing.completed %}
			Completed {{listing.completed}}
			{% else %}
			Pending
			{% endif %}
		</td>
		</tr>
		{% endfor %}

		{% for mlssheet in mlssheets %}
		<tr>
		<td><a href="{% url 'mlssheet details' mlssheet.id %}">MLS Sheet / Attachements</a></td>
		<td>{{mlssheet.address}}</td>
		<td>{{mlssheet.created}}</td>
		<td>
			{% if mlssheet.completed %}
			Completed {{mlssheet.completed}}
			{% else %}
			Pending
			{% endif %}
		</td>
		</tr>
		{% endfor %}

		{% for mls_search in mls_searches %}
		<tr>
		<td><a href="{% url 'mlssearch details' mls_search.id %}">MLS Search</a></td>
		<td>{{mls_search.full_name}}</td>
		<td>{{mls_search.created}}</td>
		<td>
			{% if mls_search.completed %}
			Completed {{mls_search.completed}}
			{% else %}
			Pending
			{% endif %}
		</td>
		</tr>
		{% endfor %}

		{% for dotloop in dotloops %}
		<tr>
		<td><a href="{% url 'dotloop details' dotloop.id %}">Dotloop</a></td>
		<td>{{dotloop.address}}</td>
		<td>{{dotloop.created}}</td>
		<td>
			{% if dotloop.completed %}
			Completed {{dotloop.cpmpleted}}
			{% else %}
			Pending
			{% endif %}
		</td>
		</tr>
		{% endfor %}
<br>
<br>
{% endblock %}

TeamMembers/templates/pendings.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<table style="width: 100%;border-collapse: collapse;">
	<tr bgcolor="#ADD8E6">
		<th style="border: 1px solid #bbb;padding: 5px;">Request</th>
		<th style="border: 1px solid #bbb;padding: 5px;">Address / Client</th>
		<th style="border: 1px solid #bbb;padding: 5px;">Request Time</th>
		<th style="border: 1px solid #bbb;padding: 5px;">Status</th>
	</tr>
	
		{% for offer in offers %}
		<tr>
		<td><a href="{% url 'offer details' offer.id %}">Offer</a></td>
		<td>{{offer.address}}</td>
		<td>{{offer.created}}</td>
		<td>
			{% if offer.completed %}
			Completed {{offer.completed}}
			{% else %}
			Pending
			{% endif %}
		</td>
		</tr>
		{% endfor %}

		{% for addendum in addendums %}
		<tr>
		<td><a href="{% url 'addendum details' addendum.id %}">Addendum</a></td>
		<td>{{addendum.address}}</td>
		<td>{{addendum.created}}</td>
		<td>
			{% if addendum.completed %}
			Completed {{addendum.completed}}
			{% else %}
			Pending
			{% endif %}
		</td>
		</tr>
		{% endfor %}

		{% for listing in listings %}
		<tr>
		<td><a href="{% url 'listing details' listing.id %}">Listing</a></td>
		<td>{{listing.address}}</td>
		<td>{{listing.created}}</td>
		<td>
			{% if listing.completed %}
			Completed {{listing.completed}}
			{% else %}
			Pending
			{% endif %}
		</td>
		</tr>
		{% endfor %}

		{% for mlssheet in mlssheets %}
		<tr>
		<td><a href="{% url 'mlssheet details' mlssheet.id %}">MLS Sheet / Attachements</a></td>
		<td>{{mlssheet.address}}</td>
		<td>{{mlssheet.created}}</td>
		<td>
			{% if mlssheet.completed %}
			Completed {{mlssheet.completed}}
			{% else %}
			Pending
			{% endif %}
		</td>
		</tr>
		{% endfor %}

		{% for mls_search in mls_searches %}
		<tr>
		<td><a href="{% url 'mlssearch details' mls_search.id %}">MLS Search</a></td>
		<td>{{mls_search.full_name}}</td>
		<td>{{mls_search.created}}</td>
		<td>
			{% if mls_search.completed %}
			Completed {{mls_search.completed}}
			{% else %}
			Pending
			{% endif %}
		</td>
		</tr>
		{% endfor %}

		{% for dotloop in dotloops %}
		<tr>
		<td><a href="{% url 'dotloop details' dotloop.id %}">Dotloop</a></td>
		<td>{{dotloop.address}}</td>
		<td>{{dotloop.created}}</td>
		<td>
			{% if dotloop.completed %}
			Completed {{dotloop.cpmpleted}}
			{% else %}
			Pending
			{% endif %}
		</td>
		</tr>
		{% endfor %}
<br>
<br>

{% endblock %}

TeamMembers/templates/requested.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<table style="width: 100%;border-collapse: collapse;">
	<tr bgcolor="#ADD8E6">
		<th style="border: 1px solid #bbb;padding: 5px;">Request</th>
		<th style="border: 1px solid #bbb;padding: 5px;">Address / Client</th>
		<th style="border: 1px solid #bbb;padding: 5px;">Request Time</th>
		<th style="border: 1px solid #bbb;padding: 5px;">Status</th>
	</tr>
	
		{% for offer in offers %}
		<tr>
		<td><a href="{% url 'offer details' offer.id %}">Offer</a></td>
		<td>{{offer.address}}</td>
		<td>{{offer.created}}</td>
		<td>
			{% if offer.completed %}
			Completed {{offer.completed}}
			{% else %}
			Pending
			{% endif %}
		</td>
		</tr>
		{% endfor %}

		{% for addendum in addendums %}
		<tr>
		<td><a href="{% url 'addendum details' addendum.id %}">Addendum</a></td>
		<td>{{addendum.address}}</td>
		<td>{{addendum.created}}</td>
		<td>
			{% if addendum.completed %}
			Completed {{addendum.completed}}
			{% else %}
			Pending
			{% endif %}
		</td>
		</tr>
		{% endfor %}

		{% for listing in listings %}
		<tr>
		<td><a href="{% url 'listing details' listing.id %}">Listing</a></td>
		<td>{{listing.address}}</td>
		<td>{{listing.created}}</td>
		<td>
			{% if listing.completed %}
			Completed {{listing.completed}}
			{% else %}
			Pending
			{% endif %}
		</td>
		</tr>
		{% endfor %}

		{% for mlssheet in mlssheets %}
		<tr>
		<td><a href="{% url 'mlssheet details' mlssheet.id %}">MLS Sheet / Attachements</a></td>
		<td>{{mlssheet.address}}</td>
		<td>{{mlssheet.created}}</td>
		<td>
			{% if mlssheet.completed %}
			Completed {{mlssheet.completed}}
			{% else %}
			Pending
			{% endif %}
		</td>
		</tr>
		{% endfor %}

		{% for mls_search in mls_searches %}
		<tr>
		<td><a href="{% url 'mlssearch details' mls_search.id %}">MLS Search</a></td>
		<td>{{mls_search.full_name}}</td>
		<td>{{mls_search.created}}</td>
		<td>
			{% if mls_search.completed %}
			Completed {{mls_search.completed}}
			{% else %}
			Pending
			{% endif %}
		</td>
		</tr>
		{% endfor %}

		{% for dotloop in dotloops %}
		<tr>
		<td><a href="{% url 'dotloop details' dotloop.id %}">Dotloop</a></td>
		<td>{{dotloop.address}}</td>
		<td>{{dotloop.created}}</td>
		<td>
			{% if dotloop.completed %}
			Completed {{dotloop.cpmpleted}}
			{% else %}
			Pending
			{% endif %}
		</td>
		</tr>
		{% endfor %}

</table>
<br>
<br>
{% endblock %}